development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: weixin_development 
  pool: 5
  username: weixin
  password: weixin123
  host: 112.124.63.18
  port: 3306


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: weixin_release
  pool: 5
  username: weixin	
  password: weixin123
  host: 112.124.63.18
  port: 3306
