development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: weixin_development 
  pool: 5
  username: tiancheng
  password: tiancheng
  host: 211.144.76.98
  port: 3306


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: weixin_release
  pool: 5
  username: tiancheng
  password: tiancheng
  host: 211.144.76.98
  port: 3306
